### PR TITLE
add input, exclude options to filter verb

### LINKED ISSUE #2: Add include, exlude options to filter verb
Priority: High
Target verb: filter

* Destructive feature: Rename `topic` option to `exclude` option.
* New feature: Add `include` option.

### PR DESCRIPTION
**Pull request by KeisukeShima**
Closes #2

### CODE REVIEW

**Comment by KeisukeShima** [comment]
TODO: Update readme

**Comment by KeisukeShima** [comment]
DONE

**Comment by hayato-m126** [comment]
I think filter program needs to do reindex in it's process.
https://github.com/ros2/rosbag2/blob/master/rosbag2_py/test/test_reindexer.py

I check filtered bag using ros2 bag info,  topic name still remain with topic count 0.
Please see below.

```shell
~/data/sample/sample
❯ ros2 bag info input_bag/

Files:             input_bag_0.db3
Bag size:          263.4 MiB
Storage id:        sqlite3
Duration:          29.955s
Start:             Apr  3 2020 16:00:55.244 (1585897255.244)
End:               Apr  3 2020 16:01:25.199 (1585897285.199)
Messages:          5338
Topic information: Topic: /sensing/gnss/ublox/fix_velocity | Type: geometry_msgs/msg/TwistWithCovarianceStamped | Count: 30 | Serialization Format: cdr
                   Topic: /sensing/gnss/ublox/nav_sat_fix | Type: sensor_msgs/msg/NavSatFix | Count: 30 | Serialization Format: cdr
                   Topic: /sensing/gnss/ublox/navpvt | Type: ublox_msgs/msg/NavPVT | Count: 30 | Serialization Format: cdr
                   Topic: /sensing/imu/tamagawa/imu_raw | Type: sensor_msgs/msg/Imu | Count: 856 | Serialization Format: cdr
                   Topic: /sensing/lidar/left/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 300 | Serialization Format: cdr
                   Topic: /sensing/lidar/right/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 300 | Serialization Format: cdr
                   Topic: /sensing/lidar/top/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 289 | Serialization Format: cdr
                   Topic: /vehicle/status/control_mode | Type: autoware_vehicle_msgs/msg/ControlMode | Count: 876 | Serialization Format: cdr
                   Topic: /vehicle/status/shift | Type: autoware_vehicle_msgs/msg/ShiftStamped | Count: 876 | Serialization Format: cdr
                   Topic: /vehicle/status/steering | Type: autoware_vehicle_msgs/msg/Steering | Count: 876 | Serialization Format: cdr
                   Topic: /vehicle/status/twist | Type: geometry_msgs/msg/TwistStamped | Count: 875 | Serialization Format: cdr


~/data/sample/sample
❯ ros2 bag filter input_bag/ -o filtered_exclude -x "/sensing/lidar/top/velodyne_packets"
[INFO 1630315196.644233539] [rosbag2_storage]: Opened database 'input_bag/input_bag_0.db3' for READ_ONLY.
[INFO 1630315196.645883228] [rosbag2_storage]: Opened database 'filtered_exclude/filtered_exclude_0.db3' for READ_WRITE.

~/data/sample/sample
❯ ros2 bag info filtered_exclude/

Files:             filtered_exclude_0.db3
Bag size:          53.4 MiB
Storage id:        sqlite3
Duration:          29.955s
Start:             Apr  3 2020 16:00:55.244 (1585897255.244)
End:               Apr  3 2020 16:01:25.199 (1585897285.199)
Messages:          5049
Topic information: Topic: /vehicle/status/shift | Type: autoware_vehicle_msgs/msg/ShiftStamped | Count: 876 | Serialization Format: cdr
                   Topic: /vehicle/status/control_mode | Type: autoware_vehicle_msgs/msg/ControlMode | Count: 876 | Serialization Format: cdr
                   Topic: /sensing/lidar/top/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 0 | Serialization Format: cdr
                   Topic: /vehicle/status/twist | Type: geometry_msgs/msg/TwistStamped | Count: 875 | Serialization Format: cdr
                   Topic: /sensing/lidar/right/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 300 | Serialization Format: cdr
                   Topic: /sensing/imu/tamagawa/imu_raw | Type: sensor_msgs/msg/Imu | Count: 856 | Serialization Format: cdr
                   Topic: /vehicle/status/steering | Type: autoware_vehicle_msgs/msg/Steering | Count: 876 | Serialization Format: cdr
                   Topic: /sensing/lidar/left/velodyne_packets | Type: velodyne_msgs/msg/VelodyneScan | Count: 300 | Serialization Format: cdr
                   Topic: /sensing/gnss/ublox/navpvt | Type: ublox_msgs/msg/NavPVT | Count: 30 | Serialization Format: cdr
                   Topic: /sensing/gnss/ublox/nav_sat_fix | Type: sensor_msgs/msg/NavSatFix | Count: 30 | Serialization Format: cdr
                   Topic: /sensing/gnss/ublox/fix_velocity | Type: geometry_msgs/msg/TwistWithCovarianceStamped | Count: 30 | Serialization Format: cdr
```

**Comment by KeisukeShima** [comment]
I agree that if you want to completely erase a topic, we need to run reindex.

**Comment by KeisukeShima** [comment]
@hayato-m126  Added a `reindex` function after the `writer` variable was destroyed, at c983b1a.

The following is the result. Notice that topics with a count of 0 have been removed.

```fish
ros2bag_extensions on  feature/add-filter-option [?] 
❯ ros2 bag info ~/autoware.proj/rosbag2_2021_08_20-12_28_24/ | grep /system/emergency/turn_signal_cmd
                   Topic: /system/emergency/turn_signal_cmd | Type: autoware_vehicle_msgs/msg/TurnSignal | Count: 203 | Serialization Format: cdr

ros2bag_extensions on  feature/add-filter-option [?] 
❯ ros2 bag filter ~/autoware.proj/rosbag2_2021_08_20-12_28_24/ -o rosbag2_filtered-x -x "/system/emergency/turn_signal_cmd" "/autoware/driving_capability"
[INFO 1630318951.263051916] [rosbag2_storage]: Opened database '/home/shima/autoware.proj/rosbag2_2021_08_20-12_28_24/rosbag2_2021_08_20-12_28_24_0.db3' for READ_ONLY.
[INFO 1630318951.270852169] [rosbag2_storage]: Opened database 'rosbag2_filtered-x/rosbag2_filtered-x_0.db3' for READ_WRITE.
[INFO 1630318952.109838432] [rosbag2_cpp]: Beginning reindexing bag in directory: rosbag2_filtered-x
[INFO 1630318952.110438460] [rosbag2_storage]: Opened database 'rosbag2_filtered-x/rosbag2_filtered-x_0.db3' for READ_ONLY.
[INFO 1630318952.138709573] [rosbag2_cpp]: Reindexing complete.

ros2bag_extensions on  feature/add-filter-option [?] 
❯ ros2 bag info rosbag2_filtered-x/ | grep /system/emergency/turn_signal_cmd
```

**Review by hayato-m126 — APPROVED** [review]
I checked this PR working well with the bag on my PC.
Very good PR

**Pull request merged**
